spring:
  datasource:
    url: jdbc:mysql://43.139.203.74:3306/eairp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: VrkLDMnev34hEdqX
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20
  data:
    redis:
      host: 43.139.203.74
      port: 6379
      password: KFfSczDdyHV7Up2t
      jedis:
        pool:
          max-active: 20
          max-wait: 100
          max-idle: 20
          min-idle: 5
      timeout: 10000